#import "../backmatter/glossaire.typ": *

= Introduction <sec:introduction>

Type Ia supernovae are among the most important tools of modern cosmology, and their explosion mechanism, a thermonuclear deflagration in a degenerate carbon-oxygen white dwarf, remains an active area of research. A key ingredient in modeling these explosions is the speed at which the deflagration flame itself propagates, a quantity that depends on the local density, chemical composition, and electron fraction of the fuel, and that cannot currently be resolved directly in global explosion simulations.

This report presents the work carried out during a three-month _Projet de Recherche_ (PRe) internship at the Heidelberg Institute for Theoretical Studies (HITS), within the Physics of Stellar Objects group, aimed at characterizing this laminar flame speed across a range of physical conditions using the stellar hydrodynamics code #gls("phlegethon"). Starting from no prior background in either astrophysics or large-scale numerical simulation, the internship combined learning the physical and numerical formalism underlying the code, running and validating a systematic parameter study, and developing the post-processing tools needed to extract a reliable flame speed from the resulting simulations, a task that turned out to be considerably less straightforward than initially expected.

The remainder of this report is organized as follows. Section 2 describes the working environment at HITS and the organization of the project. Section 3 introduces the astrophysical context and defines the scientific problem more precisely. Section 4 presents the scientific work itself: the mathematical and numerical formulation underlying #gls("phlegethon") (Section #ref(<sec:math_num_formulation>, supplement: none)), the setup and preliminary numerical tests carried out before the main study (Section #ref(<sec:setup_prelim>, supplement: none)), the spectator-species methodology developed to vary the electron fraction (Section #ref(<sec:ye_methodology>, supplement: none)), the data post-processing pipeline built to extract flame speeds from simulation output (Section #ref(<sec:post_processing>, supplement: none)), the physical and numerical challenges encountered along the way (Section #ref(<sec:challenges>, supplement: none)), the results obtained to date (Section #ref(<sec:results>, supplement: none)), and a chronological account of the project (Section #ref(<sec:planning>, supplement: none)). Section 5 concludes the report and outlines the work that remains to be done.
