#import "../backmatter/glossaire.typ": *

= Conclusion and Perspectives <sec:conclusion>

This project set out with three objectives (Section 3.4): deriving a fitting formula for the laminar deflagration flame speed $v_l = f(rho, X_i, Y_e)$, validating #gls("phlegethon") against the existing literature on conductive flames, and documenting the resulting post-processing tools for reuse within the group.

The second and third objectives have largely been met. A self-similar simulation design (Section #ref(<sec:setup_prelim>, supplement: none)) makes it possible to sweep density and composition at a roughly constant computational cost per simulation, and the resulting flame speeds agree with #cite(<timmes1992>, form: "prose") to within a factor of a few for $rho ≳ 5 times 10^8$ g/cm#super[3] (Section #ref(<sec:results>, supplement: none)). A complete post-processing pipeline was developed from scratch over the course of the internship: flame-front detection, an exponential relaxation fit motivated by the classical theory of traveling combustion waves, a robust, non-parametric cross-check against it, and a set of diagnostics ($tau \/ T_"span"$, `agree`) that flag unreliable extractions rather than silently returning them (Section #ref(<sec:post_processing>, supplement: none)). This tooling, together with the scripts used to generate and scan the simulation parameter space, is intended to remain usable by the PSO group beyond the scope of this internship.

The first objective, a combined fitting formula depending on all three of $rho$, $X_i$, and $Y_e$, remains incomplete. Two things stand in its way at the time of writing. First, the low-density regime ($rho lt.tilde 5 times 10^8$ g/cm#super[3]) is not yet resolved: Section #ref(<sec:challenges>, supplement: none) traced this to $tau$ growing disproportionately fast relative to $t_max$ as density decreases, a behavior confirmed empirically but not yet explained physically. Second, the $Y_e$ sweep itself (Section #ref(<sec:ye_methodology>, supplement: none)) has not been carried out beyond $Y_e = 0.5$, so the Ne40 spectator methodology and the Schwab-derived box-scaling correction remain validated only in principle, not against simulation results.

Several of the difficulties encountered along the way were not primarily physical. The most significant, a labeling bug that silently defaulted every simulation's $Y_e$ to $0.5$ regardless of its true composition (Section #ref(<sec:ye_bug>, supplement: none)), cost a substantial amount of time before being identified, and only came to light once results were cross-checked against multiple independent extraction methods rather than trusted individually. This turned out to be one of the more instructive parts of the project: for a numerical study of this kind, validating the post-processing pipeline itself is as necessary as validating the underlying physics, and the two are not always easy to tell apart from the output alone.

== Perspectives <sec:perspectives>

Several concrete directions follow directly from the state described above:

- *Resolving the low-density transient.* A precise characterization of the $tau$-density relation identified in Section #ref(<sec:tau_speed_relation>, supplement: none), and correspondingly longer $t_max$ values at low density, are needed before the validation of Section #ref(<sec:results>, supplement: none) can be considered complete across the full density range.
- *Completing the $Y_e$ sweep.* Extending the simulations of Section #ref(<sec:ye_methodology>, supplement: none) to $Y_e != 0.5$ would test the Ne40 spectator methodology and the Schwab-derived correction directly, rather than relying on the working assumptions of Section #ref(<sec:ye_limitations>, supplement: none).
- *The combined fitting formula.* Once both of the above are addressed, fitting $v_l(rho, X_i, Y_e)$ across the full three-parameter grid becomes possible, delivering on the project's original objective.
- *Larger nuclear networks.* The 56-species network remains non-functional, most likely due to the $O(n^3)$ scaling of the dense-matrix linear algebra used by the network solver as network size grows (Section #ref(<sec:network_selection>, supplement: none)). A sparse-matrix reformulation, discussed further in Appendix #ref(<sec:appendix_b>, supplement: none), is a natural next step, and would also bring the 35-species results used throughout this work closer to the large-network results of #cite(<timmes1992>, form: "prose").
- *Beyond 1D.* As noted in Section 3.3, this study was deliberately restricted to a planar 1D geometry. Extending the validated post-processing pipeline to multi-dimensional simulations would allow the flame speed formula, once derived, to be tested against curvature and Rayleigh-Taylor effects absent from the present setup.

Beyond the specific scientific results, this internship provided a first sustained experience with high-performance computational astrophysics: working with an actively developed research code, debugging a numerical pipeline end to end rather than a single script, and communicating results, including unresolved problems, to a research group on a weekly basis. The gap between a simulation producing a number and that number being trustworthy turned out to be the central, recurring theme of the project.
